import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';
import "./globals.css";

const geistSans = Geist({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <NextTopLoader
          color="linear-gradient(to right, #ffffff, #E1DCEE)" // Optional: Initial gradient (CSS-based)
          height={6} // Customize height
          showSpinner={false} // Optional: Hide spinner
      />
      {/*<Header />*/}
        {children}
      </body>
    </html>
  );
}
