import type { Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <NextTopLoader
          color="linear-gradient(to right, #ffffff, #E1DCEE)" // Optional: Initial gradient (CSS-based)
          height={6} // Customize height
          showSpinner={false} // Optional: Hide spinner
      />
      {/*<Header />*/}
        {children}
      </body>
    </html>
  );
}
